#!/bin/bash
# ===========================================================================
# build 
# Wilmer Gaona Romero <wgaonar@.gmail.com>
#    Cuernavaca, Morelos
#
# 1.0 /  22 marzo 2022
# ===========================================================================

if [ $# -eq 0 ]
  then
  echo "Error, usage: ./build file.cpp"
else
  filename=${1%.*}
  echo "Building BeagleBone Application: $filename.cpp"
  g++ -std=c++17 ../../Programs/BeagleCPP/Sources/RAINBOWCOLORS.cpp ../../Programs/BeagleCPP/Sources/SYSFILEACCESS.cpp ../../Programs/BeagleCPP/Sources/MISCELLANEOUS.cpp ../../Programs/BeagleCPP/Sources/GPIO.cpp ../../Programs/BeagleCPP/Sources/LED.cpp ../../Programs/BeagleCPP/Sources/ADC.cpp ../../Programs/BeagleCPP/Sources/PWM.cpp ../../Programs/BeagleCPP/Sources/HC_SR04.cpp ../../Programs/BeagleCPP/Sources/KEYPAD_5BUTTONS.cpp ../../Programs/BeagleCPP/Sources/SERVO.cpp ../../Programs/BeagleCPP/Sources/POSITION_SERVO.cpp ../../Programs/BeagleCPP/Sources/DCMOTOR.cpp ../../Programs/BeagleCPP/Sources/L298N.cpp ThunderRobotClass.cpp $filename.cpp -lpthread -o $filename.out -Wno-psabi
echo "Finished. Execute it: sudo ./$filename.out"
fi